#! /bin/sh

export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin
export LD_LIBRARY_PATH=/lib:/lib/public:/lib/private
KERNELVER=2.6.21.5

mount -t tmpfs tmpfs -osize=1k /dev
mkdir /dev/net
ln -s /var/log/log /dev/log
ln -s /dev/ram1 /dev/ram
makedevs -d /etc/devtable /

mount -t proc proc /proc
/bin/mount -a

mkdir -p /var/log /var/run /var/state/dhcp /var/ppp /var/udhcpd /var/zebra /var/siproxd /var/cache /var/lib/misc

exec > /var/log/init-stdout.log
exec 2> /var/log/init-stderr.log

echo
echo "Loading drivers and kernel modules... "
echo

ifconfig lo 127.0.0.1 netmask 255.0.0.0 broadcast 127.255.255.255 up

test -e /lib/modules/$KERNELVER/extra/pktflow.ko && insmod /lib/modules/$KERNELVER/extra/pktflow.ko
test -e /lib/modules/$KERNELVER/extra/pktcmf.ko && insmod /lib/modules/$KERNELVER/extra/pktcmf.ko
test -e /lib/modules/$KERNELVER/extra/profdrvdd.ko && insmod /lib/modules/$KERNELVER/extra/profdrvdd.ko
test -e /lib/modules/$KERNELVER/extra/bcmxtmcfg.ko && insmod /lib/modules/$KERNELVER/extra/bcmxtmcfg.ko
test -e /lib/modules/$KERNELVER/extra/atmapi.ko && insmod /lib/modules/$KERNELVER/extra/atmapi.ko
test -e /lib/modules/$KERNELVER/extra/atmbonding.ko && insmod /lib/modules/$KERNELVER/extra/atmbonding.ko
test -e /lib/modules/$KERNELVER/extra/atmbondingeth.ko && insmod /lib/modules/$KERNELVER/extra/atmbondingeth.ko
test -e /lib/modules/$KERNELVER/extra/adsldd.ko && insmod /lib/modules/$KERNELVER/extra/adsldd.ko
test -e /lib/modules/$KERNELVER/extra/blaa_dd.ko && insmod /lib/modules/$KERNELVER/extra/blaa_dd.ko
test -e /lib/modules/$KERNELVER/extra/bcmprocfs.ko && insmod /lib/modules/$KERNELVER/extra/bcmprocfs.ko
# test -e /lib/modules/$KERNELVER/kernel/net/ipv6/ipv6.ko && insmod /lib/modules/$KERNELVER/kernel/net/ipv6/ipv6.ko
test -e /lib/modules/$KERNELVER/kernel/net/atm/br2684.ko && insmod /lib/modules/$KERNELVER/kernel/net/atm/br2684.ko
test -e /lib/modules/$KERNELVER/extra/bcm_enet.ko && insmod /lib/modules/$KERNELVER/extra/bcm_enet.ko
test -e /lib/modules/$KERNELVER/extra/bcmsw.ko && insmod /lib/modules/$KERNELVER/extra/bcmsw.ko && ifconfig bcmsw up
test -e /lib/modules/$KERNELVER/extra/bcm_usb.ko && insmod /lib/modules/$KERNELVER/extra/bcm_usb.ko
test -e /lib/modules/$KERNELVER/extra/wl.ko && insmod /lib/modules/$KERNELVER/extra/wl.ko
test -e /lib/modules/$KERNELVER/extra/dspdd.ko && insmod /lib/modules/$KERNELVER/extra/dspdd.ko
test -e /lib/modules/$KERNELVER/extra/endpointdd.ko && insmod /lib/modules/$KERNELVER/extra/endpointdd.ko
test -e /lib/modules/$KERNELVER/extra/p8021ag.ko && insmod /lib/modules/$KERNELVER/extra/p8021ag.ko
# 3g modules
# test -e /lib/modules/$KERNELVER/kernel/drivers/usb/serial/usbserial.ko && insmod /lib/modules/$KERNELVER/kernel/drivers/usb/serial/usbserial.ko
# test -e /lib/modules/$KERNELVER/kernel/drivers/usb/serial/option.ko && insmod /lib/modules/$KERNELVER/kernel/drivers/usb/serial/option.ko
# other modules
test -e /lib/modules/$KERNELVER/extra/isdn.ko && insmod /lib/modules/$KERNELVER/extra/isdn.ko
test -e /lib/modules/$KERNELVER/kernel/drivers/isdn/capi/capi.ko && insmod /lib/modules/$KERNELVER/kernel/drivers/isdn/capi/capi.ko 
test -e /lib/modules/$KERNELVER/extra/bcmgpon.ko && insmod /lib/modules/$KERNELVER/extra/bcmgpon.ko RESETONLOS=1 omciGemPortMap=1
test -e /lib/modules/$KERNELVER/extra/bcmgpon.ko && insmod /etc/gpon/modules/gpio.ko

ifconfig eth0 0.0.0.0 up
ifconfig wl0 0.0.0.0 up
brctl addbr br0
brctl addif br0 eth0
brctl addif br0 wl0
ifconfig br0 192.168.5.2 netmask 255.255.255.240 broadcast 192.168.5.15 up

dnsmasq

dropbear

# if ifconfig br1 > /dev/null 2>&1; then
# 	# set default gateway using the ip from the br1 interface
# 	gateway="`ifconfig br1 | grep "inet addr" | awk -F: '{print $2}' |\
# 		awk '{print $1}' | awk -F. '{print $1 "." $2 "." $3}'`".1
# 	route add default gw $gateway

# 	# translate lan ip addresses to the br1 ip address
# 	/usr/sbin/iptables -t nat -A POSTROUTING -o br1 -j MASQUERADE

# 	# activate linux ip forwarding
# 	echo 1 > /proc/sys/net/ipv4/ip_forward
# fi
